package es.multitiendaMike.hibernate;
// Generated 15 feb 2022 16:57:30 by Hibernate Tools 5.5.7.Final

import java.util.Objects;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Cancion generated by hbm2java
 */
@Entity
public class Cancion implements java.io.Serializable {

	@Id
	@GeneratedValue
	private Long id;
	
	private String nombre;
	private String enlaceCancion;
	private Long fkPlaylist;
	private Long fkGenero;

	public Cancion() {
	}

	public Cancion(String nombre, String enlaceCancion, Long fkPlaylist, Long fkGenero) {
		this.nombre = nombre;
		this.enlaceCancion = enlaceCancion;
		this.fkPlaylist = fkPlaylist;
		this.fkGenero = fkGenero;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEnlaceCancion() {
		return this.enlaceCancion;
	}

	public void setEnlaceCancion(String enlaceCancion) {
		this.enlaceCancion = enlaceCancion;
	}

	public Long getFkPlaylist() {
		return this.fkPlaylist;
	}

	public void setFkPlaylist(Long fkPlaylist) {
		this.fkPlaylist = fkPlaylist;
	}

	public Long getFkGenero() {
		return this.fkGenero;
	}

	public void setFkGenero(Long fkGenero) {
		this.fkGenero = fkGenero;
	}

	@Override
	public int hashCode() {
		return Objects.hash(enlaceCancion, fkGenero, fkPlaylist, id, nombre);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cancion other = (Cancion) obj;
		return Objects.equals(enlaceCancion, other.enlaceCancion) && Objects.equals(fkGenero, other.fkGenero)
				&& Objects.equals(fkPlaylist, other.fkPlaylist) && Objects.equals(id, other.id)
				&& Objects.equals(nombre, other.nombre);
	}

	@Override
	public String toString() {
		return "Cancion [id=" + id + ", nombre=" + nombre + ", enlaceCancion=" + enlaceCancion + ", fkPlaylist="
				+ fkPlaylist + ", fkGenero=" + fkGenero + "]";
	}
	
	

}
