package es.multitiendaMike.hibernate;
// Generated 18 feb 2022 15:29:31 by Hibernate Tools 5.5.7.Final

/**
 * Cancion generated by hbm2java
 */
public class Cancion implements java.io.Serializable {

	private long id;
	private Genero genero;
	private Playlist playlist;
	private String enlaceCancion;
	private String nombre;

	public Cancion() {
	}

	public Cancion(long id) {
		this.id = id;
	}

	public Cancion(long id, Genero genero, Playlist playlist, String enlaceCancion, String nombre) {
		this.id = id;
		this.genero = genero;
		this.playlist = playlist;
		this.enlaceCancion = enlaceCancion;
		this.nombre = nombre;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Genero getGenero() {
		return this.genero;
	}

	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	public Playlist getPlaylist() {
		return this.playlist;
	}

	public void setPlaylist(Playlist playlist) {
		this.playlist = playlist;
	}

	public String getEnlaceCancion() {
		return this.enlaceCancion;
	}

	public void setEnlaceCancion(String enlaceCancion) {
		this.enlaceCancion = enlaceCancion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
