package es.multitiendaMike.hibernate;
// Generated 18 feb 2022 15:29:31 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero implements java.io.Serializable {

	private long id;
	private String nombre;
	private Set cancions = new HashSet(0);

	public Genero() {
	}

	public Genero(long id) {
		this.id = id;
	}

	public Genero(long id, String nombre, Set cancions) {
		this.id = id;
		this.nombre = nombre;
		this.cancions = cancions;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCancions() {
		return this.cancions;
	}

	public void setCancions(Set cancions) {
		this.cancions = cancions;
	}

}
