package es.multitiendaMike.hibernate;
// Generated 15 feb 2022 16:57:30 by Hibernate Tools 5.5.7.Final

/**
 * Genero generated by hbm2java
 */
public class Genero implements java.io.Serializable {

	private Long id;
	private String nombre;

	public Genero() {
	}

	public Genero(String nombre) {
		this.nombre = nombre;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
