package es.multitiendaMike.hibernate;
// default package
// Generated 18 feb 2022 17:00:30 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Playlist generated by hbm2java
 */
public class Playlist implements java.io.Serializable {

	private long id;
	private String nombre;
	private int valoracion;
	private Set cancions = new HashSet(0);

	public Playlist() {
	}

	public Playlist(long id, int valoracion) {
		this.id = id;
		this.valoracion = valoracion;
	}

	public Playlist(long id, String nombre, int valoracion, Set cancions) {
		this.id = id;
		this.nombre = nombre;
		this.valoracion = valoracion;
		this.cancions = cancions;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(int valoracion) {
		this.valoracion = valoracion;
	}

	public Set getCancions() {
		return this.cancions;
	}

	public void setCancions(Set cancions) {
		this.cancions = cancions;
	}

}
