package es.multitiendaMike.hibernate;
// Generated 15 feb 2022 16:57:30 by Hibernate Tools 5.5.7.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Playlist generated by hbm2java
 */
@Entity
public class Playlist implements java.io.Serializable {

	@Id
	@GeneratedValue
	private Long id;
	private String nombre;
	private int valoracion;

	public Playlist() {
	}

	public Playlist(String nombre, int valoracion) {
		this.nombre = nombre;
		this.valoracion = valoracion;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(int valoracion) {
		this.valoracion = valoracion;
	}

}
